In [ ]:
import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [2]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]

array_list = np.array(object = list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [3]:
list_

['1', '2', '3', '4', '5']

In [ ]:
Yes, there is a difference in the data types of the variables list_ and array_list. The variable list_ is a Python list,
whereas array_list is a NumPy array.

In [ ]:
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [4]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)


print("Data type of list_:", type(list_))
for element in list_:
    print("Data type of element in list_:", type(element))


print("Data type of array_list:", type(array_list))
for element in array_list:
    print("Data type of element in array_list:", type(element))


Data type of list_: <class 'list'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of array_list: <class 'numpy.ndarray'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>


In [ ]:
Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [15]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object = list_, dtype = int)
list_



['1', '2', '3', '4', '5']

In [16]:
array_list

array([1, 2, 3, 4, 5])

In [17]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object = list_, dtype = int)

print("Data type of list_:", type(list_))
for element in list_:
    print("Data type of element in list_:", type(element))

print("Data type of array_list:", type(array_list))
for element in array_list:
    print("Data type of element in array_list:", type(element))

Data type of list_: <class 'list'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of array_list: <class 'numpy.ndarray'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>


In [ ]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)
Q4. Write a code to find the following characteristics of variable, num_array:

(i)	 shape

(ii) size

In [1]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
num_array.shape

(2, 3)

In [2]:
num_array.size

6

In [ ]:
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).

In [4]:
import numpy as np
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
zeros.shape

(3, 3)

In [8]:
zeros.size

9

In [ ]:
Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [12]:
import  numpy as np
iden = np.eye(5)
iden

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])